# Introduction by Example
- https://pytorch-geometric.readthedocs.io/en/latest/get_started/introduction.html

## Data Handling of Graphs
data.x: Node feature matrix with shape [num_nodes, num_node_features]

data.edge_index: Graph connectivity in COO format with shape [2, num_edges] and type torch.long

data.edge_attr: Edge feature matrix with shape [num_edges, num_edge_features]

data.y: Target to train against (may have arbitrary shape), e.g., node-level targets of shape [num_nodes, *] or graph-level targets of shape [1, *]

data.pos: Node position matrix with shape [num_nodes, num_dimensions]


- We show a simple example of an unweighted and undirected graph with three nodes and four edges. Each node contains exactly one feature:

In [1]:
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1, 1, 2],
                           [1, 0, 2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index)
# >>> Data(edge_index=[2, 4], x=[3, 1])

In [2]:
data

Data(x=[3, 1], edge_index=[2, 4])

In [ ]:
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1],
                           [1, 0],
                           [1, 2],
                           [2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index.t().contiguous())

In [4]:
print(data.keys)

['x', 'edge_index']


In [5]:
data['x']

tensor([[-1.],
        [ 0.],
        [ 1.]])

In [6]:
data['edge_index']

tensor([[0, 1, 1, 2],
        [1, 0, 2, 1]])

In [7]:
for key, item in data:
    print(f'{key} found in data')

x found in data
edge_index found in data


In [ ]:
data.num_nodes

In [ ]:
data.num_edges

In [ ]:
data.num_node_features

In [ ]:
data.has_isolated_nodes()

In [ ]:
data.has_self_loops()

In [ ]:
data.is_directed()

In [ ]:
# Transfer data object to GPU.
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
data = data.to(device)

## Common Benchmark Datasets

In [9]:
from torch_geometric.datasets import TUDataset

dataset = TUDataset(root='../dataset_example/ENZYMES', name='ENZYMES')

Extracting ../dataset_example/ENZYMES/ENZYMES/ENZYMES.zip
Processing...
Done!


In [10]:
dataset

ENZYMES(600)

In [11]:
len(dataset)

600

In [12]:
dataset.num_classes

6

In [13]:
dataset.num_node_features

3

In [14]:
data = dataset[0]

In [15]:
data

Data(edge_index=[2, 168], x=[37, 3], y=[1])

In [20]:
data.keys

['x', 'y', 'edge_index']

In [27]:
data['x']

tensor([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])

In [28]:
data['edge_index']

tensor([[ 0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,
          3,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,
          7,  8,  8,  8,  9,  9,  9,  9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 12,
         12, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16,
         16, 16, 17, 17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 20, 20, 20,
         21, 21, 21, 21, 21, 22, 22, 22, 22, 23, 23, 23, 23, 24, 24, 24, 24, 25,
         25, 25, 25, 25, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 28, 28, 28, 28,
         28, 28, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 31, 31, 31, 32,
         32, 32, 32, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 35, 35, 35,
         35, 35, 36, 36, 36, 36],
        [ 1,  2,  3,  0,  2,  3, 24, 27,  0,  1,  3, 27, 28,  0,  1,  2,  4,  5,
         28,  3,  5,  6, 29,  3,  4,  6,  7, 29,  4,  5,  7,  8,  5,  6,  8,  9,
         10,  6,  7,  9,  7,  8, 10, 11, 12,  7,  9, 11, 12,  9, 10, 12, 26

In [29]:
data['y']

tensor([5])

In [16]:
data.is_directed()

False

In [22]:
dataset[1]['y']

tensor([5])

In [23]:
dataset[10]['y']

tensor([5])

In [24]:
dataset[5]['y']

tensor([5])

In [32]:
for i in range(0,600):
    print(dataset[i]['y'])

tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tens

- Let’s try another one! Let’s download Cora, the standard benchmark dataset for **semi-supervised graph node classification**:



In [ ]:
from torch_geometric.datasets import Planetoid

dataset = Planetoid(root='../dataset_example/Cora', name='Cora')

In [ ]:
len(dataset)

## Mini-batches 


## Data Transforms 

## Data Transforms 

## Learning Methods on Graphs 

In [33]:
from torch_geometric.datasets import Planetoid

dataset = Planetoid(root='../dataset_example/Cora', name='Cora')


Processing...
Done!


In [43]:
len(dataset[0])

6

In [34]:
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

class GCN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = GCNConv(dataset.num_node_features, 16)
        self.conv2 = GCNConv(16, dataset.num_classes)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)

        return F.log_softmax(x, dim=1)

In [41]:
dataset[0]

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])

This time, the Data objects holds a label for each node, and additional node-level attributes: train_mask, val_mask and test_mask, where

- train_mask denotes against which nodes to train (140 nodes),

- val_mask denotes which nodes to use for validation, e.g., to perform early stopping (500 nodes),

- test_mask denotes against which nodes to test (1000 nodes).

In [44]:
dataset[0]['edge_index']

tensor([[   0,    0,    0,  ..., 2707, 2707, 2707],
        [ 633, 1862, 2582,  ...,  598, 1473, 2706]])

In [35]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = GCN().to(device)
data = dataset[0].to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)

model.train()
for epoch in range(200):
    optimizer.zero_grad()
    out = model(data)
    loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
    loss.backward()
    optimizer.step()

In [36]:
device

device(type='cuda')

In [45]:
model.eval()
pred = model(data).argmax(dim=1)
correct = (pred[data.test_mask] == data.y[data.test_mask]).sum()
acc = int(correct) / int(data.test_mask.sum())
print(f'Accuracy: {acc:.4f}')


Accuracy: 0.7970


## Exercises 